---

- name: Ensure that postgres directories are exists
  file:
    state: directory
    path: "{{postgres_prefix}}/init"
    recurse: true

- name: Configure init scripts
  template:
    src: init-db.sh
    dest: "{{postgres_prefix}}/init/00_init-db.sh"
    mode: 0755

- name: Configure database
  template:
    src: postgres.conf
    dest: "{{postgres_prefix}}/postgres.conf"
  notify: postgres restart

- name: Prepare Postgres Volume
  docker_volume:
    name: "{{postgres_volume}}"

- name: Run Postgres
  community.docker.docker_container:
    name: postgres
    image: "{{postgres_image}}"
    command: "-c 'config_file=/etc/postgresql/postgresql.conf'"
    env: "{{postgres_env}}"
    volumes: "{{postgres_volumes}}"
    ports: "{{postgres_ports}}"
    memory: "{{postgres_memory|default(omit)}}"
    networks: "{{postgres_networks|default(omit)}}"
    restart_policy: unless-stopped
