#!/bin/bash

# This file was generated by Ansible for {{ ansible_fqdn }}
# Do NOT modify this file by hand!

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
{% for db in postgres_databases %}
    CREATE DATABASE {{db.name}};
{% endfor %}
{% for user in postgres_users %}
    CREATE USER {{ user.name }} WITH PASSWORD '{{user.pass}}';
{% endfor %}
{% for priv in postgres_user_privileges %}
    GRANT {{ priv.priv }} PRIVILEGES ON DATABASE {{ priv.db }} TO {{ priv.name }};
{% endfor %}
EOSQL
